/* eslint-disable react/react-in-jsx-scope */
import Head from 'next/head';
//  import Image from 'next/image'

import Hero from '@/components/Hero';
import Slider from '@/components/Slider';

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Atelier Arcadie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Atelier Arcadie" message="" />
      <Slider />
    </>
  );
}
